-- AlterTable
ALTER TABLE "setup_signatory_templates" ADD COLUMN     "appraised_date" DATE,
ADD COLUMN     "appraised_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "appraised_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "approved_date" DATE,
ADD COLUMN     "approved_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "approved_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "assessed_date" DATE,
ADD COLUMN     "assessed_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "assessed_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "city_assessor_date" DATE,
ADD COLUMN     "city_assessor_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "city_assessor_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "deputy_date" DATE,
ADD COLUMN     "deputy_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "deputy_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "provincial_assessor_date" DATE,
ADD COLUMN     "provincial_assessor_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "provincial_assessor_tpd" BOOLEAN DEFAULT false,
ADD COLUMN     "recommending_date" DATE,
ADD COLUMN     "recommending_sgd" BOOLEAN DEFAULT false,
ADD COLUMN     "recommending_tpd" BOOLEAN DEFAULT false;
