export const rptasNavigation = [
  {
    key: "rptas",
    label: "RPTAS",
    icon: "Building2",
    permissionCode: "rptas.view",
    showInSidebar: true,
    order: 10,
    children: [
      {
        key: "rptas-dashboard",
        label: "Dashboard",
        path: "/rptas",
        icon: "LayoutDashboard",
        permissionCode: "rptas.dashboard.view",
        showInSidebar: true,
        order: 1,
      },
      {
        key: "rptas-faas-records",
        label: "FAAS Records",
        path: "/rptas/faas-records",
        icon: "FileText",
        permissionCode: "rptas.faas.view",
        showInSidebar: true,
        order: 2,
      },
      {
        key: "rptas-properties",
        label: "Properties",
        path: "/rptas/properties",
        icon: "Building2",
        permissionCode: "rptas.properties.view",
        showInSidebar: true,
        order: 3,
      },
      {
        key: "rptas-assessment",
        label: "Tax Assessment",
        path: "/rptas/assessment",
        icon: "FileText",
        permissionCode: "rptas.assessment.view",
        showInSidebar: true,
        order: 4,
      },
      {
        key: "rptas-reports",
        label: "Reports",
        path: "/rptas/reports",
        icon: "BarChart3",
        permissionCode: "rptas.reports.view",
        showInSidebar: true,
        order: 5,
      },
      {
        key: "rptas-settings",
        label: "Settings",
        path: "/rptas/settings",
        icon: "Settings",
        permissionCode: "rptas.settings.view",
        showInSidebar: true,
        order: 6,
      },
      {
        key: "rptas-profile",
        label: "My Profile",
        path: "/rptas/profile",
        icon: "User",
        permissionCode: "rptas.profile.view",
        showInSidebar: true,
        order: 7,
      },
      {
        key: "rptas-data-entry",
        label: "Data Entry",
        path: "/rptas/data-entry",
        icon: "ClipboardEdit",
        permissionCode: "rptas.data_entry.view",
        showInSidebar: true,
        order: 8,
      },
      {
        key: "rptas-data-entry-v2",
        label: "RPT Management",
        path: "/rptas/data-entry-v2",
        icon: "ClipboardEdit",
        permissionCode: "rptas.data_entry.view",
        showInSidebar: true,
        order: 9,
      }
    ]
  }
];
